version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
    driver: local
